# Use a base image with the necessary dependencies
FROM ubuntu:latest

# Install required packages
RUN apt-get update && \
    apt-get install -y ncbi-blast+

# Set the working directory
WORKDIR /app

# Clean Up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Set the default command arguments
CMD ["blastn"]